name: Java CI with Maven (JDK21)

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Grants permission to create releases
	  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & Test
        run: mvn clean package

      - name: Upload JAR as Artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: my-project-jar
          path: target/*.jar

      - name: Create GitHub Release (when tagged)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar

      - name: Cleanup Target Directory
        run: rm -rf target/
